[tool.poetry]
authors = ["Flynn <wphestiraid@gmail.com>"]
description = "FastAPI base project."
license = "MIT"
name = "fast-api-base"
packages = [{include = "app"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
fastapi = {extras = ["all"], version = "^0.87.0"}
python = "3.11"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pycln = "^2.1.2"
pyright = "^1.1.279"
pytest = "^7.2.0"
pytest-asyncio = "^0.20.2"
pytest-cov = "^4.0.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
include = '\.pyi?$'
line-length = 120
preview = true
skip-string-normalization = true
target-version = ['py310']

[tool.flake8]
ignore = 'E203'
max-line-length = 120

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
multi_line_output = 3
use_parentheses = true

[tool.pycln]
all = true
